name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  audit:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run `brew audit`
        run: brew audit --new-formula Formula/voidchirp.rb
